import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import Analytics from '@/components/analytics'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="min-h-screen">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
      <Analytics/>
    </html>
  )
}
